[build]
    command = "npm run build"
    publish = "dist"

[[redirects]]
    from = "http://example.com"
    to = "https://example.com"
    status = 301
    force = true

# [[redirects]]
#    from = "/"
#    to = "/cy"
#    status = 302
#    force= true
#    conditions = {Language = ["cy"]}

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer-when-downgrade"
        Permissions-Policy = "interest-cohort=(), geolocation=(), microphone=(), camera=(), autoplay=(), fullscreen=(), payment=(), usb=(), vibrate=(), gyroscope=(), accelerometer=()"

[context.develop]
  command = "npm run build && cp ./_developHeaders ./dist/_headers && cp ./robots/staging.txt ./dist/robots.txt"

[context.master]
  command = "npm run build && cp ./robots/production.txt ./dist/robots.txt"