[build]
    command = "npm run build"
    publish = "dist"

[[redirects]]
    from = "http://example.com"
    to = "https://example.com"
    status = 301
    force = true

# [[redirects]]
#    from = "/"
#    to = "/cy"
#    status = 302
#    force= true
#    conditions = {Language = ["cy"]}

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer-when-downgrade"
        Permissions-Policy = "interest-cohort=(), geolocation=(), microphone=(), camera=(), autoplay=(), fullscreen=(), payment=(), usb=(), vibrate=(), gyroscope=(), accelerometer=()"
        Content-Security-Policy = "default-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://www.googletagmanager.com/; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://cdn.cookielaw.org https://edge.marker.io https://www.google.com/recaptcha/ https://maps.googleapis.com/ https://www.gstatic.com/recaptcha/ https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://maps.googleapis.com https://cdn.cookielaw.org https://edge.marker.io https://api.marker.io https://sessions.bugsnag.com/ https://s3.eu-west-1.amazonaws.com/; frame-src 'self' https://www.google.com/recaptcha/ https://www.googletagmanager.com https://app.netlify.com/;"

[context.develop]
  command = "npm run build && cp ./_developHeaders ./dist/_headers && cp ./robots/staging.txt ./dist/robots.txt"

[context.master]
  command = "npm run build && cp ./robots/production.txt ./dist/robots.txt"